INSERT INTO `nature` (designation, parent, tarifs, dateDebut) VALUES 
('Cartes d\'adhésion annuelles des lecteurs', null, null, NOW()), 
('Reproduction et impression de documents et archives(Tous support confondus)', null, null, NOW()), 
('Fourniture d\'enregistrements numériques', null, null, NOW()), 
('Droits d\'expertise et authenticité des archives', null, null, NOW()), 
('Formation dans le domaine des archives', null, null, NOW()), 
('Location des espaces et locaux des Archives du Maroc', null, null, NOW()), 
('Adhésion (Carte annuelle)', 1, '[\'50.00\', \'100.00\', \'25.00\', \'Gratuit\']', NOW()), 
('Repoduction sur microfilm', 2, '[\'2.00\']', NOW()), 
('Repoduction de microfilm sur papier', 2, '[\'2.50\']', NOW()), 
('Photocopie des documents administratifs... A4/A3', 2, '[\'0.50\',\'1.00\']', NOW()), 
('Photocopie demandée à distance des documents administratifs... A4/A3', 2, '[\'0.50\',\'1.00\']', NOW()), 
('Impression à partir des postes informatique (A4)', 2, '[\'1.00\']', NOW()), 
('Radio diffusion', 2, '[\'100.00\',\'500.00\']', NOW()), 
('Diffusion télévisée cryptée, noir et blanc', 2, '[\'100.00\',\'1000.00\']', NOW()), 
('Diffusion télévisée cryptée, couleur', 2, '[\'100.00\',\'2000.00\']', NOW()), 
('Diffusion télévisée non cryptée, noir et blanc', 2, '[\'100.00\',\'500.00\']', NOW()), 
('Diffusion télévisée non cryptée, couleur', 2, '[\'100.00\',\'500.00\']', NOW()), 
('Film (long métrage), noir et blanc', 2, '[\'100.00\',\'1000.00\']', NOW()), 
('Film (long métrage), couleur', 2, '[\'100.00\',\'1000.00\']', NOW()), 
('Film (moyen et court métrage), noir et blanc', 2, '[\'100.00\',\'250.00\']', NOW()), 
('Film (moyen et court métrage), couleur', 2, '[\'100.00\',\'500.00\']', NOW()), 
('Cartes et plans', 3, '[\'10.00\',\'500.00\']', NOW()), 
('Cartes postales', 3, '[\'10.00\',\'500.00\']', NOW()), 
('Photographies', 3, '[\'10.00\',\'500.00\']', NOW()), 
('plaques de verre', 3, '[\'10.00\',\'500.00\']', NOW()), 
('Manuscrits', 3, '[\'2.00\',\'500.00\']', NOW()), 
('Reproduction et visa d\'authenticité de document d\'archives', 4, '[\'300.00\']', NOW()), 
('Expertise en matiére des archives', 4, '[\'1000.00\']', NOW()), 
('Formation dans le domaine des archives', 5, '[\'200.00\']', NOW()), 
('Salle Polyvalente', 6, '[\'5000.00\',\'Gratuit\']', NOW()), 
('Galerie des Archives', 6, '[\'5000.00\',\'Gratuit\']', NOW()), 
('Tournage d\'émissions ou de films documentaires', 6, '[\'10000.00\']', NOW());